eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4000/eureka/

server:
  port: 5004

spring:
  application:
    name: demo-zuul-service

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: demo-ribbon-service
    api-b:
      path: /api-b/**
      serviceId: demo-feign-service