server:
  port: 4000

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    renewalPercentThreshold: 0.49

spring:
  application:
    name: demo-eureka-server